//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NY.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UAD_User
    {
        public UAD_User()
        {
            this.UAD_Role = new HashSet<UAD_Role>();
        }
    
        public string cUser_Id { get; set; }
        public string cUser_Name { get; set; }
        public string cUser_Password { get; set; }
        public Nullable<int> iAuthMode { get; set; }
        public string cDepName { get; set; }
        public string cEmail { get; set; }
        public string cMobilePhone { get; set; }
        public bool bStop { get; set; }
        public bool bLogined { get; set; }
        public Nullable<int> iErrorCount { get; set; }
        public Nullable<System.DateTime> dLastLoginDate { get; set; }
    
        public virtual ICollection<UAD_Role> UAD_Role { get; set; }
    }
}
