//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NY.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UAD_Role
    {
        public UAD_Role()
        {
            this.UAD_User = new HashSet<UAD_User>();
        }
    
        public string cRole_Id { get; set; }
        public string cRole_Name { get; set; }
        public string cMemo { get; set; }
        public bool bAdmin { get; set; }
    
        public virtual ICollection<UAD_User> UAD_User { get; set; }
    }
}
