//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NY.UADP.SRUserRole {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UAD_User", Namespace="http://schemas.datacontract.org/2004/07/NY.Model")]
    [System.SerializableAttribute()]
    public partial class UAD_User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NY.UADP.SRUserRole.UAD_Role[] UAD_RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bLoginedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bStopField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cDepNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cMobilePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cUser_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cUser_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cUser_PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dLastLoginDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> iAuthModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> iErrorCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NY.UADP.SRUserRole.UAD_Role[] UAD_Role {
            get {
                return this.UAD_RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.UAD_RoleField, value) != true)) {
                    this.UAD_RoleField = value;
                    this.RaisePropertyChanged("UAD_Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bLogined {
            get {
                return this.bLoginedField;
            }
            set {
                if ((this.bLoginedField.Equals(value) != true)) {
                    this.bLoginedField = value;
                    this.RaisePropertyChanged("bLogined");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bStop {
            get {
                return this.bStopField;
            }
            set {
                if ((this.bStopField.Equals(value) != true)) {
                    this.bStopField = value;
                    this.RaisePropertyChanged("bStop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cDepName {
            get {
                return this.cDepNameField;
            }
            set {
                if ((object.ReferenceEquals(this.cDepNameField, value) != true)) {
                    this.cDepNameField = value;
                    this.RaisePropertyChanged("cDepName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cEmail {
            get {
                return this.cEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.cEmailField, value) != true)) {
                    this.cEmailField = value;
                    this.RaisePropertyChanged("cEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cMobilePhone {
            get {
                return this.cMobilePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.cMobilePhoneField, value) != true)) {
                    this.cMobilePhoneField = value;
                    this.RaisePropertyChanged("cMobilePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cUser_Id {
            get {
                return this.cUser_IdField;
            }
            set {
                if ((object.ReferenceEquals(this.cUser_IdField, value) != true)) {
                    this.cUser_IdField = value;
                    this.RaisePropertyChanged("cUser_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cUser_Name {
            get {
                return this.cUser_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.cUser_NameField, value) != true)) {
                    this.cUser_NameField = value;
                    this.RaisePropertyChanged("cUser_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cUser_Password {
            get {
                return this.cUser_PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.cUser_PasswordField, value) != true)) {
                    this.cUser_PasswordField = value;
                    this.RaisePropertyChanged("cUser_Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dLastLoginDate {
            get {
                return this.dLastLoginDateField;
            }
            set {
                if ((this.dLastLoginDateField.Equals(value) != true)) {
                    this.dLastLoginDateField = value;
                    this.RaisePropertyChanged("dLastLoginDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> iAuthMode {
            get {
                return this.iAuthModeField;
            }
            set {
                if ((this.iAuthModeField.Equals(value) != true)) {
                    this.iAuthModeField = value;
                    this.RaisePropertyChanged("iAuthMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> iErrorCount {
            get {
                return this.iErrorCountField;
            }
            set {
                if ((this.iErrorCountField.Equals(value) != true)) {
                    this.iErrorCountField = value;
                    this.RaisePropertyChanged("iErrorCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UAD_Role", Namespace="http://schemas.datacontract.org/2004/07/NY.Model")]
    [System.SerializableAttribute()]
    public partial class UAD_Role : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NY.UADP.SRUserRole.UAD_User[] UAD_UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cMemoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cRole_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cRole_NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NY.UADP.SRUserRole.UAD_User[] UAD_User {
            get {
                return this.UAD_UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UAD_UserField, value) != true)) {
                    this.UAD_UserField = value;
                    this.RaisePropertyChanged("UAD_User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bAdmin {
            get {
                return this.bAdminField;
            }
            set {
                if ((this.bAdminField.Equals(value) != true)) {
                    this.bAdminField = value;
                    this.RaisePropertyChanged("bAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cMemo {
            get {
                return this.cMemoField;
            }
            set {
                if ((object.ReferenceEquals(this.cMemoField, value) != true)) {
                    this.cMemoField = value;
                    this.RaisePropertyChanged("cMemo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cRole_Id {
            get {
                return this.cRole_IdField;
            }
            set {
                if ((object.ReferenceEquals(this.cRole_IdField, value) != true)) {
                    this.cRole_IdField = value;
                    this.RaisePropertyChanged("cRole_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cRole_Name {
            get {
                return this.cRole_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.cRole_NameField, value) != true)) {
                    this.cRole_NameField = value;
                    this.RaisePropertyChanged("cRole_Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommonResult", Namespace="http://schemas.datacontract.org/2004/07/NY.Server.Utility")]
    [System.SerializableAttribute()]
    public partial class CommonResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, object> RetDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, object> RetData {
            get {
                return this.RetDataField;
            }
            set {
                if ((object.ReferenceEquals(this.RetDataField, value) != true)) {
                    this.RetDataField = value;
                    this.RaisePropertyChanged("RetData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRUserRole.IUserRoleService")]
    public interface IUserRoleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRoleService/AddUser", ReplyAction="http://tempuri.org/IUserRoleService/AddUserResponse")]
        NY.UADP.SRUserRole.CommonResult AddUser(NY.UADP.SRUserRole.UAD_User model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRoleService/AddUser", ReplyAction="http://tempuri.org/IUserRoleService/AddUserResponse")]
        System.Threading.Tasks.Task<NY.UADP.SRUserRole.CommonResult> AddUserAsync(NY.UADP.SRUserRole.UAD_User model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRoleService/EditUser", ReplyAction="http://tempuri.org/IUserRoleService/EditUserResponse")]
        NY.UADP.SRUserRole.CommonResult EditUser(NY.UADP.SRUserRole.UAD_User model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRoleService/EditUser", ReplyAction="http://tempuri.org/IUserRoleService/EditUserResponse")]
        System.Threading.Tasks.Task<NY.UADP.SRUserRole.CommonResult> EditUserAsync(NY.UADP.SRUserRole.UAD_User model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRoleService/GetUserById", ReplyAction="http://tempuri.org/IUserRoleService/GetUserByIdResponse")]
        NY.UADP.SRUserRole.UAD_User GetUserById(string strId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRoleService/GetUserById", ReplyAction="http://tempuri.org/IUserRoleService/GetUserByIdResponse")]
        System.Threading.Tasks.Task<NY.UADP.SRUserRole.UAD_User> GetUserByIdAsync(string strId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRoleService/GetUserList", ReplyAction="http://tempuri.org/IUserRoleService/GetUserListResponse")]
        NY.UADP.SRUserRole.UAD_User[] GetUserList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRoleService/GetUserList", ReplyAction="http://tempuri.org/IUserRoleService/GetUserListResponse")]
        System.Threading.Tasks.Task<NY.UADP.SRUserRole.UAD_User[]> GetUserListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRoleService/AddRole", ReplyAction="http://tempuri.org/IUserRoleService/AddRoleResponse")]
        NY.UADP.SRUserRole.CommonResult AddRole(NY.UADP.SRUserRole.UAD_Role model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRoleService/AddRole", ReplyAction="http://tempuri.org/IUserRoleService/AddRoleResponse")]
        System.Threading.Tasks.Task<NY.UADP.SRUserRole.CommonResult> AddRoleAsync(NY.UADP.SRUserRole.UAD_Role model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRoleService/EditRole", ReplyAction="http://tempuri.org/IUserRoleService/EditRoleResponse")]
        NY.UADP.SRUserRole.CommonResult EditRole(NY.UADP.SRUserRole.UAD_Role model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRoleService/EditRole", ReplyAction="http://tempuri.org/IUserRoleService/EditRoleResponse")]
        System.Threading.Tasks.Task<NY.UADP.SRUserRole.CommonResult> EditRoleAsync(NY.UADP.SRUserRole.UAD_Role model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRoleService/GetRoleById", ReplyAction="http://tempuri.org/IUserRoleService/GetRoleByIdResponse")]
        NY.UADP.SRUserRole.UAD_Role GetRoleById(string strId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRoleService/GetRoleById", ReplyAction="http://tempuri.org/IUserRoleService/GetRoleByIdResponse")]
        System.Threading.Tasks.Task<NY.UADP.SRUserRole.UAD_Role> GetRoleByIdAsync(string strId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRoleService/GetRoleList", ReplyAction="http://tempuri.org/IUserRoleService/GetRoleListResponse")]
        NY.UADP.SRUserRole.UAD_Role[] GetRoleList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRoleService/GetRoleList", ReplyAction="http://tempuri.org/IUserRoleService/GetRoleListResponse")]
        System.Threading.Tasks.Task<NY.UADP.SRUserRole.UAD_Role[]> GetRoleListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserRoleServiceChannel : NY.UADP.SRUserRole.IUserRoleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserRoleServiceClient : System.ServiceModel.ClientBase<NY.UADP.SRUserRole.IUserRoleService>, NY.UADP.SRUserRole.IUserRoleService {
        
        public UserRoleServiceClient() {
        }
        
        public UserRoleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserRoleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserRoleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserRoleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public NY.UADP.SRUserRole.CommonResult AddUser(NY.UADP.SRUserRole.UAD_User model) {
            return base.Channel.AddUser(model);
        }
        
        public System.Threading.Tasks.Task<NY.UADP.SRUserRole.CommonResult> AddUserAsync(NY.UADP.SRUserRole.UAD_User model) {
            return base.Channel.AddUserAsync(model);
        }
        
        public NY.UADP.SRUserRole.CommonResult EditUser(NY.UADP.SRUserRole.UAD_User model) {
            return base.Channel.EditUser(model);
        }
        
        public System.Threading.Tasks.Task<NY.UADP.SRUserRole.CommonResult> EditUserAsync(NY.UADP.SRUserRole.UAD_User model) {
            return base.Channel.EditUserAsync(model);
        }
        
        public NY.UADP.SRUserRole.UAD_User GetUserById(string strId) {
            return base.Channel.GetUserById(strId);
        }
        
        public System.Threading.Tasks.Task<NY.UADP.SRUserRole.UAD_User> GetUserByIdAsync(string strId) {
            return base.Channel.GetUserByIdAsync(strId);
        }
        
        public NY.UADP.SRUserRole.UAD_User[] GetUserList() {
            return base.Channel.GetUserList();
        }
        
        public System.Threading.Tasks.Task<NY.UADP.SRUserRole.UAD_User[]> GetUserListAsync() {
            return base.Channel.GetUserListAsync();
        }
        
        public NY.UADP.SRUserRole.CommonResult AddRole(NY.UADP.SRUserRole.UAD_Role model) {
            return base.Channel.AddRole(model);
        }
        
        public System.Threading.Tasks.Task<NY.UADP.SRUserRole.CommonResult> AddRoleAsync(NY.UADP.SRUserRole.UAD_Role model) {
            return base.Channel.AddRoleAsync(model);
        }
        
        public NY.UADP.SRUserRole.CommonResult EditRole(NY.UADP.SRUserRole.UAD_Role model) {
            return base.Channel.EditRole(model);
        }
        
        public System.Threading.Tasks.Task<NY.UADP.SRUserRole.CommonResult> EditRoleAsync(NY.UADP.SRUserRole.UAD_Role model) {
            return base.Channel.EditRoleAsync(model);
        }
        
        public NY.UADP.SRUserRole.UAD_Role GetRoleById(string strId) {
            return base.Channel.GetRoleById(strId);
        }
        
        public System.Threading.Tasks.Task<NY.UADP.SRUserRole.UAD_Role> GetRoleByIdAsync(string strId) {
            return base.Channel.GetRoleByIdAsync(strId);
        }
        
        public NY.UADP.SRUserRole.UAD_Role[] GetRoleList() {
            return base.Channel.GetRoleList();
        }
        
        public System.Threading.Tasks.Task<NY.UADP.SRUserRole.UAD_Role[]> GetRoleListAsync() {
            return base.Channel.GetRoleListAsync();
        }
    }
}
